"""Initial schema with all 7 tables

Revision ID: 9492f697882b
Revises: 
Create Date: 2026-01-05 11:48:27.660615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9492f697882b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_sqlx_migrations')
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Dot-notation event name (e.g., player.died, item.extracted)',
               existing_nullable=False)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Event-specific metadata in JSON format',
               existing_nullable=True)
    op.drop_index(op.f('idx_audit_timestamp'), table_name='audit_logs')
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_table_comment(
        'audit_logs',
        existing_comment='Structured event log for debugging and analytics',
        schema=None
    )
    op.drop_table_comment(
        'currencies',
        existing_comment='Player currency balances with economic floor enforcement',
        schema=None
    )
    op.alter_column('item_definitions', 'max_stack',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('item_definitions', 'properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Item-specific stats in JSON (e.g., bomb range, vest absorption)',
               existing_nullable=True)
    op.drop_table_comment(
        'item_definitions',
        existing_comment='Static item definitions with stats and metadata',
        schema=None
    )
    op.alter_column('match_participants', 'loadout',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Immutable snapshot of gear at match start (for death = lose all)',
               existing_nullable=False)
    op.alter_column('match_participants', 'loot_extracted',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Items successfully extracted from match',
               existing_nullable=True)
    op.alter_column('match_participants', 'kill_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('match_participants', 'damage_dealt',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_table_comment(
        'match_participants',
        existing_comment='Player participation in matches with outcome tracking',
        schema=None
    )
    op.alter_column('matches', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Match state machine: initializing → active → completed/aborted',
               existing_nullable=False)
    op.alter_column('matches', 'server_address',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Game Server process endpoint (IP:port)',
               existing_nullable=True)
    op.alter_column('matches', 'max_players',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('8'))
    op.drop_index(op.f('idx_match_started'), table_name='matches')
    op.create_index('idx_match_started', 'matches', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.drop_table_comment(
        'matches',
        existing_comment='Match metadata and lifecycle tracking',
        schema=None
    )
    op.alter_column('players', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='bcrypt hashed password',
               existing_nullable=False)
    op.alter_column('players', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_table_comment(
        'players',
        existing_comment='Core player authentication and profile data',
        schema=None
    )
    op.alter_column('stash_items', 'is_equipped',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='Items equipped for next raid',
               existing_server_default=sa.text('false'))
    op.drop_table_comment(
        'stash_items',
        existing_comment='Player persistent inventory (stash)',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'stash_items',
        'Player persistent inventory (stash)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('stash_items', 'is_equipped',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='Items equipped for next raid',
               existing_server_default=sa.text('false'))
    op.create_table_comment(
        'players',
        'Core player authentication and profile data',
        existing_comment=None,
        schema=None
    )
    op.alter_column('players', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('players', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt hashed password',
               existing_nullable=False)
    op.create_table_comment(
        'matches',
        'Match metadata and lifecycle tracking',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_match_started', table_name='matches', postgresql_ops={'started_at': 'DESC'})
    op.create_index(op.f('idx_match_started'), 'matches', [sa.literal_column('started_at DESC')], unique=False)
    op.alter_column('matches', 'max_players',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('8'))
    op.alter_column('matches', 'server_address',
               existing_type=sa.VARCHAR(length=100),
               comment='Game Server process endpoint (IP:port)',
               existing_nullable=True)
    op.alter_column('matches', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Match state machine: initializing → active → completed/aborted',
               existing_nullable=False)
    op.create_table_comment(
        'match_participants',
        'Player participation in matches with outcome tracking',
        existing_comment=None,
        schema=None
    )
    op.alter_column('match_participants', 'damage_dealt',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('match_participants', 'kill_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('match_participants', 'loot_extracted',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Items successfully extracted from match',
               existing_nullable=True)
    op.alter_column('match_participants', 'loadout',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Immutable snapshot of gear at match start (for death = lose all)',
               existing_nullable=False)
    op.create_table_comment(
        'item_definitions',
        'Static item definitions with stats and metadata',
        existing_comment=None,
        schema=None
    )
    op.alter_column('item_definitions', 'properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Item-specific stats in JSON (e.g., bomb range, vest absorption)',
               existing_nullable=True)
    op.alter_column('item_definitions', 'max_stack',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_table_comment(
        'currencies',
        'Player currency balances with economic floor enforcement',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'audit_logs',
        'Structured event log for debugging and analytics',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_audit_timestamp', table_name='audit_logs', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_audit_timestamp'), 'audit_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Event-specific metadata in JSON format',
               existing_nullable=True)
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Dot-notation event name (e.g., player.died, item.extracted)',
               existing_nullable=False)
    op.create_table('_sqlx_migrations',
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('installed_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('checksum', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('_sqlx_migrations_pkey'))
    )
    # ### end Alembic commands ###
